### ISSUE TITLE
Module not found: Error: Can't resolve 'v-code-diff'

### ISSUE THREAD

**Issue by taylous** [Shimada666/v-code-diff#67]
i loaded it to use that module in the **vue3 app.** 
> according to the way in readme

however, the same error occurs in the console as the title.
> Module not found: Error: Can't resolve 'v-code-diff'...

The same error occurs in pure **vue cli app.**

***what is the cause?***

## local environment
- vue/cli: 5.0.8
- vue: 3.2.13

**Comment by Shimada666** [comment]
Vue-cli is outdated. For Vue3 projects, I recommend using [create-vue](https://github.com/vuejs/create-vue) to create a Vue scaffold based on Vite.
Also, I haven't created a Vue3 project using vue-cli5. Could you provide a minimum reproducible repository created with vue-cli5?

**Comment by taylous** [comment]
@Shimada666 
unfortunately, i can't now create Codesandbox or a minimum reproducible repository... sorry... 😭

however, when i created an app with **the latest vue-cli**(5.0.8), i have an error even if I only install v-code-diff without any setting...

as you said, i made `Vite` and installed v-code-diff, **but the following error occurred.** 🤔
> X [ERROR] Failed to resolve entry for package "v-code-diff". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

**Comment by Shimada666** [comment]
No problem, I will provide a demo example using StackBlitz tonight. You can refer to it for installation.
Alternatively, you can create a GitHub repository with the problematic code, and I can take a look at it for you.

**Comment by taylous** [comment]
is demo example not yet ready? 🤔
before uploading a problem code, i want to compare  my code with the correct code.

**Comment by Shimada666** [comment]
> @Shimada666 thank you for your kindness 😀
> 
> is demo example not yet ready? 🤔 before uploading a problem code, i want to compare my code with the correct code.

I'm sorry, I've been quite busy lately. You can refer to [it](https://github.com/Shimada666/v-code-diff/tree/master/example/npm/vue3_vite). I hope it can help you

**Comment by taylous** [comment]
@Shimada666 

when I tested it on codesandbox, `Module Not Found Error` occured.
[Code SandBox](https://codesandbox.io/s/stupefied-field-spdyzc?file=/src/App.vue)

**Comment by taylous** [comment]
@Shimada666 

do you see the wrong code in the contents of codesandbox? 🤔
it seems to me that something is not compatible with the latest version of vue. (or CLI...)

**Comment by Shimada666** [comment]
<img width="907" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/33391300/3d8162f4-1b22-453f-afb9-16ffa838fb14">

hi, I have reproduced this error on StackBlitz. I found that it was caused by the failure to execute the postinstall script. The postinstall script of the plugin reads the Vue version of the project and copies the corresponding version files to the "dist" directory. However, as you can see, this script didn't execute for some unknown reason. When I manually executed it, the files were copied correctly, and the project was able to run properly. It also runs fine in the local environment, you can give it a try.

<img width="1589" alt="image" src="https://github.com/Shimada666/v-code-diff/assets/33391300/da7b8046-8d81-4b55-b078-7fc3d8df854b">

**Comment by taylous** [comment]
@Shimada666 

it works fine!!! 🎉

thank you for quick response. 😃
> will the problem that postinstall.js not run normally be fixed and updated?

**Comment by Shimada666** [comment]
I'm glad I was able to resolve your issue! Currently, I'm not sure why this problem occurred, but I will take some time to investigate it further. 😃
